"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ShieldCheck,
  Zap,
  Search,
  Lock,
  Eye,
  Smartphone,
  FileText,
  Sparkles,
  ArrowRight,
  CheckCircle2,
  Globe,
  Bot,
  Activity,
  Award,
} from "lucide-react";
import { motion } from "framer-motion";

export default function LandingPage() {
  const [urlInput, setUrlInput] = useState("");
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleQuickScan = (e: React.FormEvent) => {
    e.preventDefault();
    if (!urlInput.trim()) return;
    setLoading(true);
    router.push(`/dashboard/scanner?url=${encodeURIComponent(urlInput)}`);
  };

  const features = [
    {
      icon: Search,
      title: "SEO Optimization",
      desc: "Meta title/desc analysis, OpenGraph, Schema.org, canonical tags, heading order & keyword density.",
      badge: "25% Weight",
    },
    {
      icon: Zap,
      title: "Performance & Web Vitals",
      desc: "TTFB measurement, HTML/CSS/JS payload sizes, render-blocking scripts, and Core Web Vitals estimates.",
      badge: "25% Weight",
    },
    {
      icon: Eye,
      title: "Accessibility (WCAG 2.1)",
      desc: "Image alt tag audit, ARIA landmark roles, color contrast ratios, form label associations, and keyboard navigation.",
      badge: "15% Weight",
    },
    {
      icon: Lock,
      title: "Security & Headers",
      desc: "HTTPS verification, HSTS, Content Security Policy (CSP), X-Frame-Options clickjacking, and cookie security flags.",
      badge: "15% Weight",
    },
    {
      icon: Smartphone,
      title: "Mobile Responsiveness",
      desc: "Viewport configuration, responsive image scaling, tap target layout sizes, and mobile rendering.",
      badge: "10% Weight",
    },
    {
      icon: FileText,
      title: "Content & Readability",
      desc: "Flesch-Kincaid readability scoring, word count sufficiency, spam indicator checks, and CTA quality.",
      badge: "10% Weight",
    },
  ];

  return (
    <div className="relative overflow-hidden bg-slate-950 text-slate-100">
      {/* Background Decorative Gradients */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px] bg-gradient-to-tr from-blue-600/20 via-indigo-500/10 to-transparent blur-3xl pointer-events-none -z-10" />

      {/* HERO SECTION */}
      <section className="relative pt-24 pb-20 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full border border-blue-500/30 bg-blue-500/10 text-blue-400 text-xs font-semibold mb-6 shadow-inner"
        >
          <Sparkles className="w-3.5 h-3.5 text-amber-400" />
          <span>Powered by Google Gemini AI & Multi-Dimension Engine</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl sm:text-6xl lg:text-7xl font-extrabold tracking-tight text-white max-w-4xl mx-auto leading-[1.1]"
        >
          Analyze. Understand. <br />
          <span className="gradient-text">Improve Your Website.</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-6 text-lg sm:text-xl text-slate-400 max-w-2xl mx-auto leading-relaxed"
        >
          Comprehensive AI website auditing platform. Get instant SEO, Performance, Accessibility, Security, Mobile, and UI insights with copy-paste code fixes generated by Google Gemini.
        </motion.p>

        {/* QUICK URL SCANNER INPUT */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mt-10 max-w-2xl mx-auto"
        >
          <form onSubmit={handleQuickScan} className="relative flex items-center p-2 rounded-2xl glass-panel border border-slate-700/80 shadow-2xl focus-within:ring-2 focus-within:ring-blue-500">
            <div className="pl-4 text-slate-400">
              <Globe className="w-5 h-5" />
            </div>
            <input
              type="text"
              value={urlInput}
              onChange={(e) => setUrlInput(e.target.value)}
              placeholder="Enter website URL (e.g., example.com)"
              className="w-full px-4 py-3.5 bg-transparent text-sm text-white placeholder-slate-500 focus:outline-none"
              required
            />
            <button
              type="submit"
              disabled={loading}
              className="px-6 py-3.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs flex items-center space-x-2 transition-all shadow-lg shadow-blue-600/30 shrink-0"
            >
              <span>{loading ? "Analyzing..." : "Audit Now"}</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </form>
          <p className="mt-3 text-xs text-slate-500 flex items-center justify-center space-x-4">
            <span>✓ Zero installation required</span>
            <span>✓ Sub-second real scanning</span>
            <span>✓ Instant Gemini AI Code Fixes</span>
          </p>
        </motion.div>
      </section>

      {/* DASHBOARD PREVIEW STATS BANNER */}
      <section className="py-12 border-y border-slate-800/80 bg-slate-900/40">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
          <div>
            <span className="text-3xl sm:text-4xl font-extrabold text-white">7+</span>
            <span className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mt-1">
              Audit Dimensions
            </span>
          </div>
          <div>
            <span className="text-3xl sm:text-4xl font-extrabold text-blue-400">100%</span>
            <span className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mt-1">
              Real Analysis Logic
            </span>
          </div>
          <div>
            <span className="text-3xl sm:text-4xl font-extrabold text-emerald-400">&lt; 1s</span>
            <span className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mt-1">
              Scan Speed
            </span>
          </div>
          <div>
            <span className="text-3xl sm:text-4xl font-extrabold text-amber-400">Gemini 2.5</span>
            <span className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mt-1">
              AI Recommendation Engine
            </span>
          </div>
        </div>
      </section>

      {/* FEATURES GRID SECTION */}
      <section id="features" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-xs font-bold uppercase tracking-widest text-blue-500">Comprehensive Inspection</h2>
          <p className="text-3xl sm:text-4xl font-extrabold text-white mt-2">
            7 Dimensions of Website Health
          </p>
          <p className="text-slate-400 text-sm mt-3">
            Every audit evaluates your web app against strict standards to deliver actionable code fixes.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f, i) => {
            const Icon = f.icon;
            return (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                viewport={{ once: true }}
                className="p-6 rounded-2xl border border-slate-800 bg-slate-900/60 glass-panel hover:border-slate-700 transition-all"
              >
                <div className="flex items-center justify-between mb-4">
                  <div className="p-3 rounded-xl bg-blue-600/10 text-blue-400 border border-blue-500/20">
                    <Icon className="w-6 h-6" />
                  </div>
                  <span className="px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 text-[11px] font-semibold">
                    {f.badge}
                  </span>
                </div>
                <h3 className="text-lg font-bold text-white">{f.title}</h3>
                <p className="text-xs text-slate-400 mt-2 leading-relaxed">{f.desc}</p>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* PRICING SECTION */}
      <section id="pricing" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto border-t border-slate-800">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-xs font-bold uppercase tracking-widest text-blue-500">Transparent Plans</h2>
          <p className="text-3xl sm:text-4xl font-extrabold text-white mt-2">Scale Your Web Auditing</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Starter */}
          <div className="p-8 rounded-3xl border border-slate-800 bg-slate-900/50 flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-bold text-white">Starter</h3>
              <p className="text-xs text-slate-400 mt-1">For freelancers & developers</p>
              <div className="mt-6">
                <span className="text-4xl font-extrabold text-white">$29</span>
                <span className="text-slate-400 text-xs"> / month</span>
              </div>
              <ul className="mt-6 space-y-3 text-xs text-slate-300">
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>50 Scans / Month</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>7-Dimension Audit Engine</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>PDF & CSV Exports</span></li>
              </ul>
            </div>
            <Link href="/dashboard/scanner" className="mt-8 w-full py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs text-center block transition-colors">
              Start Free Trial
            </Link>
          </div>

          {/* Pro */}
          <div className="p-8 rounded-3xl border-2 border-blue-500 bg-slate-900 relative flex flex-col justify-between shadow-2xl shadow-blue-500/10">
            <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 px-3 py-1 rounded-full bg-blue-600 text-white text-[10px] font-extrabold tracking-wider uppercase">
              Most Popular
            </span>
            <div>
              <h3 className="text-lg font-bold text-white">Pro SaaS</h3>
              <p className="text-xs text-slate-400 mt-1">For growing marketing teams & agencies</p>
              <div className="mt-6">
                <span className="text-4xl font-extrabold text-white">$79</span>
                <span className="text-slate-400 text-xs"> / month</span>
              </div>
              <ul className="mt-6 space-y-3 text-xs text-slate-300">
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Unlimited Website Scans</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Google Gemini AI Code Fixes</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Scan-Aware Interactive AI Chat</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Shareable Passwordless Links</span></li>
              </ul>
            </div>
            <Link href="/dashboard/scanner" className="mt-8 w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs text-center block transition-all shadow-lg shadow-blue-600/30">
              Upgrade to Pro
            </Link>
          </div>

          {/* Enterprise */}
          <div className="p-8 rounded-3xl border border-slate-800 bg-slate-900/50 flex flex-col justify-between">
            <div>
              <h3 className="text-lg font-bold text-white">Enterprise</h3>
              <p className="text-xs text-slate-400 mt-1">Custom infrastructure & API access</p>
              <div className="mt-6">
                <span className="text-4xl font-extrabold text-white">$199</span>
                <span className="text-slate-400 text-xs"> / month</span>
              </div>
              <ul className="mt-6 space-y-3 text-xs text-slate-300">
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Custom API Access</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>Dedicated Cloud Run Instance</span></li>
                <li className="flex items-center space-x-2"><CheckCircle2 className="w-4 h-4 text-emerald-400" /><span>White-label PDF Branding</span></li>
              </ul>
            </div>
            <Link href="/dashboard/settings" className="mt-8 w-full py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs text-center block transition-colors">
              Contact Sales
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="py-12 border-t border-slate-800 text-slate-500 text-xs text-center">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center space-x-2">
            <ShieldCheck className="w-4 h-4 text-blue-500" />
            <span className="text-slate-300 font-bold">AI Website Auditor</span>
          </div>
          <p>&copy; 2026 AI Website Auditor. Production Ready Clean Architecture.</p>
        </div>
      </footer>
    </div>
  );
}
